version: "3.9"
services:
  bot:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PYTHONUNBUFFERED: "1"
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python tg.py"
    restart: unless-stopped
