name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          set -e
          ssh "$PROD_USER@$PROD_HOST" git -C "$DEPLOY_DIR" pull
          ssh "$PROD_USER@$PROD_HOST" "echo 'BOT_TOKEN=${BOT_TOKEN}' > \"$DEPLOY_DIR/.env\""
        env:
          PROD_USER: ${{ secrets.PROD_USER }}
          PROD_HOST: ${{ secrets.PROD_HOST }}
          DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
